config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :ideas
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  root to: 'ideas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :participations
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  def user_name
    user.name
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :person_a, class_name: 'User'
  belongs_to :person_b, class_name: 'User'

  def other_person(user)
    if user == person_a
      person_b
    else
      person_a
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas

  has_many :relationships,
    foreign_key: "person_a_id",
    dependent: :destroy

  has_many :people,
    through: :relationships,
    source: "person_b",
    class_name: "User",
    dependent: :destroy

  has_many :participations,
    dependent: :destroy

  def bidirectional_relationships
    Relationship.where(person_a_id: id).or(Relationship.where(person_b_id: id))
  end

  def people
    bidirectional_relationships.map { |relationship| relationship.other_person(self) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def create
    current_user.with_lock do
      idea = current_user.ideas.create!(idea_params)

      idea.participations.create!(user: current_user)

      participations = params[:idea][:participations].reject { |id| id == "0" }

      participations.each do |user_id|
        idea.participations.create!(user_id: user_id)
      end

      idea.save!
    end

    redirect_to action: :index
  end

  def destroy
    Idea.find(params[:id]).destroy!

    redirect_to action: :index
  end

  private

  def idea_params
    params.require(:idea).permit(:name, :location, :url)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def index
    @relationships = current_user.bidirectional_relationships
  end

  def create
    email = params[:email]

    other_user = User.find_by(email: email)

    if other_user
      current_user.relationships.create!(person_b: other_user)
      flash[:notice] = "Successfully added relationship with #{other_user.name}"
    else
      flash[:alert] = "No user found with email: #{email}"
    end

    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/ideas/index.html.erb
<h2>Ideas</h2>

<%= link_to "Relationships", relationships_path %>

<%= form_for Idea.new do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>

  <fieldset>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </fieldset>

  <fieldset>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </fieldset>

  <fieldset>
    Invite:
    <% current_user.people.each do |person| %>
      <%= f.label person.id, person.name %>
      <%= f.check_box :participations, {multiple: true, checked: true}, person.id %>
    <% end %>
  </fieldset>

  <%= f.submit %>
<% end %>

<div class="ideas">
  <% @ideas.each do |idea| %>
    <div class="idea">
      <h3><%= idea.url.present? ? link_to(idea.name, idea.url) : idea.name %></h3>
      <p><%= idea.location %></p>
      <%= idea.participations.map(&:user_name).to_sentence %>
      <%= button_to 'Destroy', idea_path(idea), method: :delete %>
      <hr>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateNight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/relationships/index.html.erb
<h2>Relationships</h2>

<%= link_to "Date Ideas", ideas_path %>

<div>
  <% @relationships.each do |relationship| %>
    <%= relationship.person_a.name %> ❤️ <%= relationship.person_b.name %>
  <% end %>
</div>


<%= form_tag(relationships_path) do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= submit_tag "Request relationship" %>
<% end %>